pipeline:
  build:
    image: plugins/docker
    repo: docker.phopen.com:5000/pwa-beetlock
    tags:
      - 1.0.0
      - 1.0
      - latest
  ssh:
    image: appleboy/drone-ssh
    host: cd.beetlock.com
    username:
      from_secret: ssh_user
    password:
      from_secret: ssh_password
    port: 22
    command_timeout: 2m
    script:
      - cd /var/opt/traefik && ./pwa-beetlock.sh
