apiVersion: apps/v1
kind: Deployment
metadata:
  name: beetlock-pwa-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beetlock-pwa
  template:
    metadata:
      labels:
        app: beetlock-pwa
    spec:
      containers:
        - name: beetlock-pwa
          image: cloud.canister.io:5000/wolnik/beetlock-pwa
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: registrypullsecret
---
apiVersion: v1
kind: Service
metadata:
  name: beetlock-pwa
spec:
  selector:
    app: beetlock-pwa
  type: NodePort # remove if using ClusterIp
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32080
  # clusterIp: none # uncomment if using ClusterIp
